### ISSUE TITLE
Missing Google meta tags

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/distill#116]
According to [this instruction](https://www.monperrus.net/martin/accurate+bibliographic+metadata+and+google+scholar), it seems like we miss the following Google meta tags for distill YAML.

It would be nicer if we could generate the following Google meta tags when provided by users in YAML.

- [ ] `citation_pdf_url`
- [ ] `citation_conference_title`
- [ ] `citation_isbn`
- [ ] `citation_firstpage`
- [ ] `citation_lastpage`
- [ ] `citation_dissertation_institution`
- [ ] `citation_technical_report_institution`
- [ ] `citation_technical_report_number`

**Comment by jooyoungseo** [comment]
Closing by #118.
